###
GET http://localhost:8000/

###
GET http://localhost:8000/pets

###
GET http://localhost:8000/pets/-1

###
GET http://localhost:8000/pets/0

###
GET http://localhost:8000/pets/3

###
GET http://localhost:8000/pets/abc

###
GET http://localhost:8000/pets/8

###
GET http://localhost:8000/boom

###
GET http://localhost:8000/about

### put a pet
PUT http://localhost:8000/pets/5
Content-Type: application/json

{
    "age": 5,
    "kind": "lion",
    "name": "Ryan"
}

### create a pet
POST http://localhost:8000/pets/
Content-Type: application/json

{
    "age": 6,
    "kind": "wolf",
    "name": "jack"
}

### patch a pet
PATCH http://localhost:8000/pets/1
Content-Type: application/json

{
    "kind": "wolf",
}

### delete a pet
DELETE http://localhost:8000/pets/7